#!/bin/bash
# Sollte in /usr/local/bin platziert werden
export http_proxy="http://127.0.0.1:8118"
conky -c ~/.conkyrc-dwm | while read -r; do xsetroot -name "$REPLY"; done &
nitrogen --restore &
xfce4-power-manager &
xfce4-volumed &
xscreensaver -no-splash &
thunar --daemon &
pnmixer &
nm-applet &
#(/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 && \
##/usr/bin/gnome-keyring-daemon --start --components=ssh && \
#/usr/bin/gnome-keyring-daemon --start --components=secrets && \
#/usr/bin/gnome-keyring-daemon --start --components=pkcs11 && \
#/usr/bin/gnome-keyring-daemon --start --components=gpg) &
synclient TapButton2=3 TabButton3=3 RBCornerButton=3 RTCornerButton=2 &
orage &
~/.dropbox-dist/dropboxd &
exec dwm
